#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env);

helper.make_plugins( [ 'art_Framework_Core',
                       'art_Framework_IO_Sources',
                       'art_Framework_Principal',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'cetlib',
                       'cetlib_except',
                       'Core',
                       'boost_filesystem',
                       'tbb',
                       'hep_concurrency'
                     ],
                     )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
